name: Security

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        pip install safety bandit pip-audit

    - name: Run safety check
      run: |
        safety check --json --output safety-report.json || true

    - name: Run pip-audit
      run: |
        pip-audit --format=json --output=pip-audit-report.json || true

    - name: Run bandit security scan
      run: |
        bandit -r raindrop_cleanup/ -f json -o bandit-report.json || true

    - name: Upload security reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: security-reports
        path: |
          safety-report.json
          pip-audit-report.json
          bandit-report.json

    - name: Check for high severity issues
      run: |
        # Check safety report for high severity issues
        if [ -f safety-report.json ]; then
          HIGH_ISSUES=$(jq '.vulnerabilities[] | select(.severity == "high")' safety-report.json || echo "[]")
          if [ "$HIGH_ISSUES" != "[]" ]; then
            echo "::error::High severity security vulnerabilities found!"
            exit 1
          fi
        fi